version: "2"

services:
  python-app:
    image: nrb-python
    environment:
      - HELP=${HELP}        # flag  show parameter help
      - VERBOSE=${VERBOSE}  # int   verbosity level 0-3
      - DEBUG=${DEBUG}      # flag  do not save output/dry run
    volumes:
      - ./:/app
      - ${SHEET_FOLDER}:/output
    entrypoint: [python, hulls2site.py]
